theme: jekyll-theme-slate
title: ["The one with the Social Data Analysis"]([The one with the Social Data Analysis](https://lunahub.github.io/Friends_social_data_analysis_2019/))
show_downloads: False
